//! Host-filesystem metadata sidecars that are never collection content.
//!
//! Copying a collection onto exFAT, FAT, or an SMB share leaves macOS with
//! nowhere to put extended attributes and resource forks, so it writes an
//! `AppleDouble` sidecar named `._<original>` beside every file that carries
//! them. An rsync of a library to an external drive therefore arrives with a
//! `._Some Game.chd` next to every `Some Game.chd`.
//!
//! These files are regenerated by the OS and hold no collection data, but they
//! inherit the original's extension, so an extension test alone treats them as
//! ROMs: they scan as phantom games, and inside a preservation dump they read
//! as files the manifest never recorded. Every walk over user-supplied
//! directories filters through here so the rule stays in one place.

use std::path::Path;

/// Prefix macOS gives `AppleDouble` sidecars on filesystems without native
/// extended-attribute support.
const APPLE_DOUBLE_PREFIX: &str = "._";

/// Names that are host-filesystem bookkeeping rather than collection content.
const METADATA_FILES: &[&str] = &[".DS_Store", "Thumbs.db", "desktop.ini"];

/// True when a file name is host-filesystem metadata rather than content.
#[must_use]
pub fn is_noise_file_name(name: &str) -> bool {
    name.starts_with(APPLE_DOUBLE_PREFIX)
        || METADATA_FILES
            .iter()
            .any(|candidate| name.eq_ignore_ascii_case(candidate))
}

/// True when a path's own file name is host-filesystem metadata.
///
/// Only the final component is tested, so a collection stored under a
/// directory that happens to match is not excluded wholesale.
#[must_use]
pub fn is_noise_path(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(is_noise_file_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn apple_double_sidecars_inherit_the_extension_they_shadow() {
        // The exact trap: an extension test alone accepts this as a ROM.
        assert!(is_noise_path(Path::new("/roms/snes/._Super Metroid.sfc")));
        assert!(!is_noise_path(Path::new("/roms/snes/Super Metroid.sfc")));
    }

    #[test]
    fn a_leading_dot_alone_is_not_a_sidecar() {
        // `.retro-junk` and `.stignore` are the archive's own dot entries.
        assert!(!is_noise_path(Path::new("/archive/.retro-junk")));
        assert!(!is_noise_path(Path::new("/archive/.stignore")));
    }

    #[test]
    fn finder_and_explorer_metadata_are_noise() {
        assert!(is_noise_path(Path::new("/roms/.DS_Store")));
        assert!(is_noise_path(Path::new("/roms/Thumbs.db")));
    }

    #[test]
    fn only_the_final_component_is_tested() {
        // A collection rooted under a noisy-looking directory still scans.
        assert!(!is_noise_path(Path::new("/._staging/roms/Game.sfc")));
    }
}
